# Generated by Django 2.0 on 2018-08-13 17:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 13, 10, 42, 11, 154999))),
                ('url', models.URLField()),
            ],
        ),
    ]
